version: '3.8'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: fastapi-app
    container_name: fastapi-container
    ports:
      - "8000:8000"  # Adjust port if necessary
    volumes:
      - ./app:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: ollama-container
    ports:
      - "11434:11434"  # Expose the Ollama API port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge